In [63]:
import textblob

with open('data/el-owl-cat.txt') as f:
    raw_verse = f.read()
f.close()

verse = textblob.TextBlob(raw_verse)
print(f'Words: {verse.words}')
print(f'Words count: {verse.word_counts}')

unique_words = sum(1 for value in verse.word_counts.values() if value == 1)
print(f'Number of unique words: {unique_words}')
highest_values = sorted(verse.word_counts.items(), key=lambda x: x[1], reverse=True)[:5]
print("10 most frequent words:")
for key, value in highest_values:
    print(f"{key}: {value}")

Words: ['The', 'Owl', 'and', 'the', 'Pussy-Cat', 'went', 'to', 'sea', 'In', 'a', 'beautiful', 'pea-green', 'boat', 'They', 'took', 'some', 'honey', 'and', 'plenty', 'of', 'money', 'Wrapped', 'up', 'in', 'a', 'five-pound', 'note', 'The', 'Owl', 'looked', 'up', 'to', 'the', 'stars', 'above', 'And', 'sang', 'to', 'a', 'small', 'guitar', 'O', 'lovely', 'Pussy', 'O', 'Pussy', 'my', 'love', 'What', 'a', 'beautiful', 'Pussy', 'you', 'are', 'You', 'are', 'You', 'are', 'What', 'a', 'beautiful', 'Pussy', 'you', 'are', 'Pussy', 'said', 'to', 'the', 'Owl', 'You', 'elegant', 'fowl', 'How', 'charmingly', 'sweet', 'you', 'sing', 'O', 'let', 'us', 'be', 'married', 'too', 'long', 'we', 'have', 'tarried', 'But', 'what', 'shall', 'we', 'do', 'for', 'a', 'ring', 'They', 'sailed', 'away', 'for', 'a', 'year', 'and', 'a', 'day', 'To', 'the', 'land', 'where', 'the', 'Bong-tree', 'grows', 'And', 'there', 'in', 'a', 'wood', 'a', 'Piggy-wig', 'stood', 'With', 'a', 'ring', 'at', 'the', 'end', 'of', 'his', 'nose',

In [64]:
import requests
stopwords = requests.get("https://raw.githubusercontent.com/fozziethebeat/S-Space/master/data/english-stop-words-large.txt").content.decode('utf 8').split ("\n")
stopwords

['a',
 "a's",
 'able',
 'about',
 'above',
 'according',
 'accordingly',
 'across',
 'actually',
 'after',
 'afterwards',
 'again',
 'against',
 "ain't",
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'an',
 'and',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'apart',
 'appear',
 'appreciate',
 'appropriate',
 'are',
 "aren't",
 'around',
 'as',
 'aside',
 'ask',
 'asking',
 'associated',
 'at',
 'available',
 'away',
 'awfully',
 'b',
 'be',
 'became',
 'because',
 'become',
 'becomes',
 'becoming',
 'been',
 'before',
 'beforehand',
 'behind',
 'being',
 'believe',
 'below',
 'beside',
 'besides',
 'best',
 'better',
 'between',
 'beyond',
 'both',
 'brief',
 'but',
 'by',
 'c',
 "c'mon",
 "c's",
 'came',
 'can',
 "can't",
 'cannot',
 'cant',
 'cause',
 'causes',
 'certain',
 'certainly',
 'changes',
 'clearly',
 'co',
 'com',
 'come',
 'c

In [65]:
not_stop_words = [k for k in verse.words if k.lower() not in stopwords]
verse = textblob.TextBlob(" ".join(not_stop_words))
print(f'Words: {verse.words}')
print(f'Words count: {verse.word_counts}')

unique_words = sum(1 for value in verse.word_counts.values() if value == 1)
print(f'Number of unique words: {unique_words}')
highest_values = sorted(verse.word_counts.items(), key=lambda x: x[1], reverse=True)[:5]
print("10 most frequent words:")
for key, value in highest_values:
    print(f"{key}: {value}")

Words: ['Owl', 'Pussy-Cat', 'sea', 'beautiful', 'pea-green', 'boat', 'honey', 'plenty', 'money', 'Wrapped', 'five-pound', 'note', 'Owl', 'looked', 'stars', 'sang', 'small', 'guitar', 'lovely', 'Pussy', 'Pussy', 'love', 'beautiful', 'Pussy', 'beautiful', 'Pussy', 'Pussy', 'Owl', 'elegant', 'fowl', 'charmingly', 'sweet', 'sing', 'married', 'long', 'tarried', 'ring', 'sailed', 'year', 'day', 'land', 'Bong-tree', 'grows', 'wood', 'Piggy-wig', 'stood', 'ring', 'end', 'nose', 'nose', 'nose', 'ring', 'end', 'nose', 'Dear', 'Pig', 'sell', 'shilling', 'ring', 'Piggy', 'married', 'day', 'Turkey', 'lives', 'hill', 'dinèd', 'mince', 'slices', 'quince', 'ate', 'runcible', 'spoon', 'hand', 'hand', 'edge', 'sand', 'danced', 'light', 'moon', 'moon', 'moon', 'danced', 'light', 'moon']
Words count: defaultdict(<class 'int'>, {'owl': 3, 'pussy-cat': 1, 'sea': 1, 'beautiful': 3, 'pea-green': 1, 'boat': 1, 'honey': 1, 'plenty': 1, 'money': 1, 'wrapped': 1, 'five-pound': 1, 'note': 1, 'looked': 1, 'stars':

In [80]:
files = [
    "data/a-3kittens.txt",
    "data/bp-tom-kitten.txt",
    "data/el-owl-cat.txt",
    "data/rc-cat-fiddle.txt",
    "data/rk-cat.txt"
]

import pandas as pd
frequency_term_document_matrix =pd.DataFrame()

for file in files:
    with open(file) as f:
        raw_verse = f.read()
    f.close()

    verse = textblob.TextBlob(raw_verse)
    not_stop_words = [k for k in verse.words if k.lower() not in stopwords]
    verse = textblob.TextBlob(" ".join(not_stop_words))
    print(f"Words: {verse.words}")
    print(f"Words count: {verse.word_counts}")

    unique_words = sum(1 for value in verse.word_counts.values() if value == 1)
    print(f"Number of unique words: {unique_words}")
    highest_values = sorted(verse.word_counts.items(), key=lambda x: x[1], reverse=True)[:10]
    print("10 most frequent words:")
    for key, value in highest_values:
        if key not in frequency_term_document_matrix.columns:
            frequency_term_document_matrix[key] = 0
        print(f"{key}: {value}")
    highest_values = {key: value for key, value in highest_values}
    frequency_term_document_matrix = frequency_term_document_matrix.append(highest_values, ignore_index=True)
frequency_term_document_matrix.fillna(0, inplace=True)
boolean_term_document_matrix = frequency_term_document_matrix.copy()  # Copy the original DataFrame
boolean_term_document_matrix[boolean_term_document_matrix >= 1] = 1
boolean_term_document_matrix

Words: ['kittens', 'Lost', 'mittens', 'began', 'cry', 'mammy', 'dear', 'sadly', 'fear', 'mittens', 'lost', 'lost', 'mittens', 'naughty', 'kittens', 'pie', 'Miew', 'miew', 'miew', 'miew', 'Miew', 'miew', 'miew', 'miew', 'kittens', 'sought', 'mittens', 'table', 'high', 'Indoors', 'scampered', 'spry', 'high', 'low', 'row', 'made', 'things', 'fly', 'Miew', 'miew', 'miew', 'miew', 'Miew', 'miew', 'miew', 'miew', 'kittens', 'Found', 'mittens', 'began', 'cry', 'mammy', 'dear', 'mittens', 'found', 'found', 'mittens', 'darling', 'kittens', 'pie', 'Purr', 'purr', 'purr', 'purr', 'Purr', 'purr', 'purr', 'purr', 'kittens', 'Put', 'mittens', 'ate', 'pie', 'mammy', 'dear', 'sadly', 'fear', 'mittens', 'soiled', 'soiled', 'mittens', 'naughty', 'kittens', 'began', 'sigh', 'Miew', 'miew', 'miew', 'miew', 'Miew', 'miew', 'miew', 'miew', 'kittens', 'Washed', 'mittens', 'hung', 'dry', 'mammy', 'dear', 'mittens', 'washed', 'washed', 'mittens', 'good', 'kittens', 'smell', 'rat', 'close', 'Hush', 'hush', 'Mie

miew  purr  mittens  kittens  began  mammy  dear  lost  cry  pie  ...  \
0   1.0   1.0      1.0      1.0    1.0    1.0   1.0   1.0  1.0  1.0  ...   
1   0.0   0.0      1.0      1.0    0.0    0.0   0.0   0.0  0.0  0.0  ...   
2   0.0   0.0      0.0      0.0    0.0    0.0   0.0   0.0  0.0  0.0  ...   
3   0.0   0.0      0.0      0.0    0.0    0.0   0.0   0.0  0.0  0.0  ...   
4   0.0   0.0      0.0      0.0    0.0    0.0   0.0   0.0  0.0  0.0  ...   

   laughed  fun  wild  woman  cave  enemy  woods  man  fire  horse  
0      0.0  0.0   0.0    0.0   0.0    0.0    0.0  0.0   0.0    0.0  
1      0.0  0.0   0.0    0.0   0.0    0.0    0.0  0.0   0.0    0.0  
2      0.0  0.0   0.0    0.0   0.0    0.0    0.0  0.0   0.0    0.0  
3      1.0  1.0   0.0    0.0   0.0    0.0    0.0  0.0   0.0    0.0  
4      0.0  0.0   1.0    1.0   1.0    1.0    1.0  1.0   1.0    1.0  

[5 rows x 45 columns]

In [81]:
import numpy as np
from scripts.DistanceHelper import get_distance, DistanceType

number_of_rows = boolean_term_document_matrix.shape[0]
number_of_columns = boolean_term_document_matrix.shape[1]
euclidean_distance_matrix = np.zeros((number_of_rows, number_of_rows))

for i, element_0 in boolean_term_document_matrix.iterrows():
    for j, element_1 in boolean_term_document_matrix.iterrows():
        euclidean_distance_matrix[i, j] = get_distance(
            element_0, element_1, number_of_columns, DistanceType.EUCLIDEAN
        )
        
euclidean_distance_matrix

array([[0.        , 4.        , 4.47213595, 4.47213595, 4.47213595],
       [4.        , 0.        , 4.47213595, 4.47213595, 4.47213595],
       [4.47213595, 4.47213595, 0.        , 4.24264069, 4.47213595],
       [4.47213595, 4.47213595, 4.24264069, 0.        , 4.        ],
       [4.47213595, 4.47213595, 4.47213595, 4.        , 0.        ]])

In [85]:

import numpy as np
from scripts.DistanceHelper import get_distance, DistanceType
from numpy import dot
from numpy.linalg import norm

number_of_rows = frequency_term_document_matrix.shape[0]
number_of_columns = frequency_term_document_matrix.shape[1]
euclidean_distance_matrix = np.zeros((number_of_rows, number_of_rows))
cosine_similarity_matrix = np.zeros((number_of_rows, number_of_rows))

for i, element_0 in frequency_term_document_matrix.iterrows():
    for j, element_1 in frequency_term_document_matrix.iterrows():
        euclidean_distance_matrix[i, j] = get_distance(
            element_0, element_1, number_of_columns, DistanceType.EUCLIDEAN
        )
        cosine_similarity_matrix[i, j] = dot(element_0, element_1)/(norm(element_0)*norm(element_1))
        
print(euclidean_distance_matrix)
print()
print(cosine_similarity_matrix)

[[  0.          74.15524257  73.58668358  72.9451849  168.84904501]
 [ 74.15524257   0.          24.41311123  22.4053565  153.91880977]
 [ 73.58668358  24.41311123   0.          10.58300524 152.67285286]
 [ 72.9451849   22.4053565   10.58300524   0.         151.6739925 ]
 [168.84904501 153.91880977 152.67285286 151.6739925    0.        ]]

[[1.         0.09248395 0.         0.         0.        ]
 [0.09248395 1.         0.         0.         0.        ]
 [0.         0.         1.         0.10724978 0.        ]
 [0.         0.         0.10724978 1.         0.19118548]
 [0.         0.         0.         0.19118548 1.        ]]
